main/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from app.views import main, send_offer, portfolio, about

urlpatterns = [
    path('', main, name='main'),
    path('portfolio/', portfolio, name='portfolio'),
    path('about/', about, name='about'),
    path('send_offer', send_offer, name='send_offer'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
import os
from PIL import Image as Image_pil

from django.db import models


class Work(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    translit = models.CharField(max_length=255, verbose_name='Транслит')
    photo = models.ImageField(verbose_name='Фото')
    photo_mobile = models.ImageField(verbose_name='Фото для мобильной версии', blank=True, null=True)
    style = models.CharField(max_length=100, verbose_name='Стиль работы', blank=True, null=True)
    for_main = models.BooleanField(default=False, verbose_name='Для главной страницы')
    order = models.IntegerField(verbose_name='Порядок вывода',  null=True, blank=True)

    class Meta:
        verbose_name = 'Работа'
        verbose_name_plural = 'Работы'
        ordering = ['order']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.pk:
            last_works = Work.objects.filter(order__isnull=False)
            for work in last_works:
                work.order += 1
                work.save()
            self.order = 1

        super().save(*args, **kwargs)
        Image_pil.open(self.photo.path).save(self.photo.path, quality=50)
        os.chmod(self.photo.path, 436)


class Image(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    image = models.ImageField(verbose_name='Изображение')
    work = models.ForeignKey(Work, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Изображение работы'
        verbose_name_plural = 'Изображения работ'

    def __str__(self):
        return '{} {}'.format(self.name, self.work)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        Image_pil.open(self.image.path).save(self.image.path, quality=50)
        os.chmod(self.image.path, 436)


class Phone(models.Model):
    number = models.CharField(max_length=255, verbose_name='Телефонный номер')
    is_active = models.BooleanField(verbose_name='Активный номер', default=False)

    class Meta:
        verbose_name = 'Номер телефона'
        verbose_name_plural = 'Номера телефонов'

    def __str__(self):
        return self.number


class Facebook(models.Model):
    url = models.CharField(max_length=255, verbose_name='Ссылка на fb')
    is_active = models.BooleanField(verbose_name='Активная ссылка', default=False)

    class Meta:
        verbose_name = 'Ссылка на FB'
        verbose_name_plural = 'Ссылки на FB'

    def __str__(self):
        return self.url


class Instagram(models.Model):
    url = models.CharField(max_length=255, verbose_name='Ссылка на instagram')
    is_active = models.BooleanField(verbose_name='Активная ссылка', default=False)

    class Meta:
        verbose_name = 'Ссылка на Instagram'
        verbose_name_plural = 'Ссылки на Instagram'

    def __str__(self):
        return self.url


class Mail(models.Model):
    email = models.CharField(max_length=255, verbose_name='Почта')
    is_active = models.BooleanField(verbose_name='Активная почта', default=False)

    class Meta:
        verbose_name = 'Адрес почты'
        verbose_name_plural = 'Адреса почты'

    def __str__(self):
        return self.email

app/views.py
import smtplib

from django.shortcuts import render, HttpResponse, get_object_or_404
from email.mime.text import MIMEText
from email.header import Header

from django.conf import settings
from app.models import Work


def get_template(request, template):
    if request.user_agent.is_mobile:
        template = 'mobile/{}'.format(template)
    return template


def main(request):
    works = list(Work.objects.filter(for_main=True).order_by('-id'))
    main_work = next_work = next2_work = prev_work = None
    if len(works) >= 4 and not request.user_agent.is_mobile:
        main_work = works.pop()
        next_work = works.pop()
        next2_work = works.pop()
        prev_work = works[0]

        works.reverse()
        works.pop()

    return render(request, get_template(request, 'main.html'),
                  {
                      'works': works, 'main_work': main_work, 'next_work': next_work,
                      'next2_work': next2_work, 'prev_work': prev_work
                  }
                  )


def portfolio(request):
    works = Work.objects.order_by('order')
    return render(request, get_template(request, 'portfolio.html'), {'works': works})


def about(request):
    return render(request, get_template(request, 'about.html'))


def send_offer(request):
    name = request.POST.get('name')

    if not name:
        return HttpResponse('Not name')
    email = request.POST.get('email')
    phone = request.POST.get('phone')
    text = request.POST.get('text')
    if not (email or phone):
        return HttpResponse('Not email of phones')

    offer = 'Имя: {} \n Email: {} \n Tелефон: {}'.format(name, email, phone)
    if not settings.DEBUG:
        smtpObj = smtplib.SMTP('smtp.yandex.ru')
        smtpObj.starttls()
        smtpObj.login(settings.EMAIL_LOGIN, settings.EMAIL_PASSWORD)

        msg = MIMEText(offer, 'plain', 'utf-8')
        msg['Subject'] = Header('Новая заявка', 'utf-8')
        msg['From'] = settings.EMAIL_LOGIN
        msg['To'] = settings.EMAIL_OFFER

        smtpObj.sendmail(msg['From'], msg['To'], msg.as_string())
        smtpObj.quit()

    return HttpResponse('ok')

app/templates/about.html
{% extends 'main.html' %}
{% load static %}


{% block title %}
<title>AristovDesign | 3D визуализация и дизайн</title>
{% endblock %}
{% block meta %}
    <meta name=description content="AristovDesign - 3D дизайн и визуализация интерьера.">
    <meta name=keywords content="3D дизайн, 3D визуализация">
{% endblock %}
{% block header %}
{% include 'include/header.html' with page="3d" %}
{% endblock %}

{% block content %}
<div class="about__wrap">
    <div class="about">
        <h1 class="about__title">Зачем нужна 3D визуализация?</h1>
        <div class="about__text">
            Для того чтобы понять, как будет выглядеть будущий дом, недостаточно иметь на руках только проект. Планы
            этажей и фасадов без применения текстур материалов не могут передать сочетания цветов "в живую". Например,
            как будет выглядеть различный кирпич и шов на самом деле? Ведь определиться с цветом кирпича – это полдела.
            Ведь восприятие цвета стены из кирпичной кладки на 30% зависит от цвета кладочного шва. Сравните две стены:
        </div>
        <div class="about__img-wrap">
            <div class="about__img" style="background-image: url({% static 'img/3d-01.jpg' %})">
            </div>
        </div>
        <div class="about__text">
            Разница есть, не правда ли? А это один и тот же кирпич, только применен разный цветной раствор для шва.
            <br><br>Какие декоративные элементы можно сделать из кирпича и в каком цветовом решении? Какого цвета и
            размера будут окна? Какую кровлю применить? А о таких нюансах, как изменит общий вид подшивка кровли или
            цвет водостока, заказчик даже не подозревает или, как правило, вообще задумывается только ближе к окончанию
            работ. Надо признать, что внешний вид дома/помещения - это то, чем каждый хочет выделиться и главное -
            сделать всё по своему вкусу. Ведь тот же автомобиль мы выбираем исходя из его цвета и наличия декоративных
            внешних элементов. Но машину со временем можно поменять, а вот изменить внешний вид дома будет очень сложно.
            Так как же увидеть заказчику свой дом или комнату еще до начала стройки?
            <br><br><strong>3D-визуализация</strong> как раз является ответом на такой вопрос в области строительства:
            проект будущего дома, с помощью компьютерной программы, воплощается в 3D-модель. Работа над 3D-моделью
            выполняется только из текстур настоящих материалов, которые можно приобрести у нас и продолжается до тех
            пор, пока заказчик не найдёт оптимального сочетания для себя.
        </div>
        <div class="about__img-wrap about__img-wrap_big">
            <div class="about__img about__img_small" style="background-image:url({% static 'img/3d-011.jpg' %})"></div>
            <div class="about__img about__img_small" style="background-image:url({% static 'img/3d-012.jpg' %})"></div>
            <div class="about__img about__img_small" style="background-image:url({% static 'img/3d-013.jpg' %})"></div>
        </div>
        <div class="about__text">
            3D-модель дает правильный взгляд на будущий дом, комнату, предмет в разных проекциях. В итоге будущий
            домовладелец получает:
            <br><br>&nbsp;• Готовое решение по внешнему виду своего будущего дома. Больше не надо ломать голову над
            нюансами, можно спокойно начинать продумывать внутреннюю планировку.
            <br><br>&nbsp;• Возможность выбора. Так как есть готовое решение и можно как сразу строить полностью дом,
            так и разбивать строительство на этапы, а материалы закупать когда это наиболее выгодно, или когда есть
            возможность.
        </div>
    </div>
</div>
{% endblock %}

app/templates/include/contacts-popup.html
<div class="contacts-popup__wrap contacts-popup__wrap_none">
    <div class="contacts-popup">
        <div class="contacts-popup__esc"></div>
        <a href="mailto:{{ mail }}" class="contacts-popup__item contacts-popup__mail">{{ mail }}</a>
        <br>
        <a href="tel:{{ phone }}" class="contacts-popup__item contacts-popup__phone">{{ phone }}</a>
    </div>
</div>

app/templates/include/contacts.html
<div class="contacts__wrap">
    <div id="contacts" class="contacts__ankor"></div>
    <div class="contacts__pillar-wrap">
        <div class="contacts__pillar"></div>
    </div>
    <div class="contacts__bg"></div>
    <div class="contacts">
        <div class="contacts__title">Оставить заявку</div>
        <div class="contacts__input-wrap">
            <input type="text" class="contacts__input contacts__input-name" placeholder="Имя">
        </div>
        <div class="contacts__input-wrap">
            <input type="text" class="contacts__input contacts__input-phone" placeholder="Телефон">
        </div>
        <div class="contacts__input-wrap contacts__input-wrap_big">
            <input type="text" class="contacts__input contacts__input_big contacts__input-email"
                placeholder="Почта (не обязательно)">
        </div>
        <div class="contacts__btn">Отправить</div>
    </div>

    <div class="contacts__pillar-wrap contacts__pillar-wrap_bottom">
        <div class="contacts__pillar contacts__pillar_bottom"></div>
    </div>
</div>

<script>
    $('.contacts__btn').click(function () {
        var name = $('.contacts__input-name').val();
        var email = $('.contacts__input-email').val();
        var phone = $('.contacts__input-phone').val();

        let phone_ver = isPhone(phone);
        let name_ver = isName(name);
        let email_ver = isEmail(email);

        if (phone_ver && name_ver) {
            if (name && (email || phone)) {
                $.ajax({
                    'type': 'POST',
                    'url': '/send_offer',
                    'data': {
                        'name': name,
                        'email': email,
                        'phone': phone,
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
                    },
                    success: function (data) {
                        $('.tnh-popup__wrap').removeClass('tnh-popup__wrap_close');
                        $('.contacts__input-name').val('');
                        $('.contacts__input-email').val('');
                        $('.contacts__input-phone').val('');
                        $('.contacts__input').removeClass('contacts__input_error');
                        ym(55984267, 'reachGoal', 'BUTTON');
                    },
                    error: function (data) {
                        alert('Заявка отправлена!')
                    }

                })
            }
        }
    })

    $('.contacts__input-phone').focusout(function () {
        if (isPhone($(this).val())) {
            ym(55984267, 'reachGoal', 'FORM');
        }
    })


    function isPhone(str) {
        if (str.length !== 11 || str.match(/[a-zA-Z]|[а-яА-Я]/g)) {
            $('.contacts__input-phone').addClass('contacts__input_error');
            return false;
        } else {
            $('.contacts__input-phone').removeClass('contacts__input_error');
            return true;
        }
    }

    function isName(str) {
        if (str.length < 3 || str.match(/[0-9]/)) {
            $('.contacts__input-name').addClass('contacts__input_error');
            return false;
        } else {
            $('.contacts__input-name').removeClass('contacts__input_error');
            return true;
        }
    }

    function isEmail(str) {
        if (str.match(/[\.]/g) && str.match(/[@]/g)) {
            $('.contacts__input-email').removeClass('contacts__input_error');
            return true;
        } else {
            $('.contacts__input-email').addClass('contacts__input_error');
            return false;
        }
    }
</script>

app/templates/include/createby.html
<a href="https://blacklink.ru" target="_blank" class="createby footer__createby">
    <span class="createby__span">b</span>
    <span class="createby__span">y</span>
    <span class="createby__span">&nbsp;</span>
    <span class="createby__span">b</span>
    <span class="createby__span">l</span>
    <span class="createby__span">a</span>
    <span class="createby__span">c</span>
    <span class="createby__span">k</span>
    <span class="createby__span">l</span>
    <span class="createby__span">i</span>
    <span class="createby__span">n</span>
    <span class="createby__span">k</span>
</a>

app/templates/include/footer.html
<div class="footer__wrap">
    <div class="footer__right">© 2019 AristovDesign.
        <br>
        <a class="footer__right_mail" href="mailto:{{ mail }}">{{ mail }}</a> </div>
    <div class="footer__social-wrap">
        <ul class="socialIcons">
            <li><a href="{{fb}}" target="_blank" class="facebook"><i class="fa fa-facebook "></i></a></li>
            <li><a href="{{instagram}}" target="_blank" class="instagram"><i class="fa fa-instagram"></i></a></li>
        </ul>
    </div>
    {% include 'include/createby.html' %}
</div>

app/templates/include/header.html
<div class="header__wrap">
    <div class="header__main">
        {% if page == 'main' %}
        <div class="header__logo header__logo_enable"></div>
        {% else %}
        <a href="/" class="header__logo"></a>
        {% endif %}
        <div class="header__menu-wrap">
            <div class="header__menu">
                {% if page == 'portfolio' %}
                <a href="/" class="header__menu-item">Главная</a>
                <div class="header__menu-item header__menu-item_activate">Портфолио</div>
                <div class="header__menu-item header__menu-item__contacts">Контакты</div>
                {% else %}
                <a href="{% url 'portfolio' %}" class="header__menu-item">Портфолио</a>
                    {% if page == 'main' %}
                    <a href="#about" class="header__menu-item header__menu-item_ankor">О нас</a>
                    {% endif %}
                <div class="header__menu-item header__menu-item__contacts">Контакты</div>
                {% endif %}
                {% if page == '3d' %}
                <a href="{% url 'about' %}" class="header__menu-item header__menu-item_activate">3D визуализация?</a>
                {% else %}
                <a href="{% url 'about' %}" class="header__menu-item">3D визуализация?</a>
                {% endif %}
                <a href="tel:{{ phone }}" class="header__menu-item header__menu-item_phone">{{ phone }}</a>
            </div>
        </div>
    </div>
    {% if page == 'main' %}
    <a href="#contacts" class="header__contactbtn header__contactbtn_main">Связаться</a>
    {% else %}
    <a href="/#_contacts" class="header__contactbtn">Связаться</a>
    {% endif %}
</div>

app/templates/include/main-window.html
{% load static %}

<div class="main-window">
    <div class="main-window__slider-prevbtn">PREV</div>
    <div class="main-window__slider-nextbtn">NEXT</div>
    <div class="main-window__slider">
        <div data-title='{{ main_work.title }}' data-href='{% url 'portfolio' %}#_{{ main_work.id }}'
            style="background-image: url({{ main_work.photo.url }})"
            class="main-window__slider-item main-window__slider-item_main"></div>
        <div data-title='{{ next_work.title }}' data-href='{% url 'portfolio' %}#_{{ next_work.id }}'
             style="background-image: url({{ next_work.photo.url }})"
            class="main-window__slider-item main-window__slider-item_next"></div>
        <div data-title='{{ next2_work.title }}' data-href='{% url 'portfolio' %}#_{{ next2_work.id }}'
              style="background-image: url({{ next2_work.photo.url }})"
            class="main-window__slider-item main-window__slider-item_next2"></div>
        {% for work in works %}
            <div data-title='{{ work.title }}' style="background-image: url({{ work.photo.url }})" data-href='{% url 'portfolio' %}#_{{ work.id }}'
             class="main-window__slider-item"></div>
        {% endfor %}
    <div data-title='{{ prev_work.title }}' style="background-image: url({{ prev_work.photo.url }})" data-href='{% url 'portfolio' %}#_{{ prev_work.id }}'
            class="main-window__slider-item main-window__slider-item_prev"></div>
    </div>
    <div class="main-window__title-wrap">
        <div class="main-window__title">AristovDesign</div>
        <br>
        <div class="main-window__subtitle">3D modeling & visualization</div>
        <div class="main-window__slider-info">
            <div class="main-window__slider-info-text"></div><div class="main-window__slider-info-text-cursor">|</div>

            <a href="/" class="main-window__slider-info-link">К проекту</a>
        </div>
    </div>
    <div class="main-window__scroll"></div>
</div>

app/templates/include/services.html
<div class="services__wrap">
    <div class="services__pillar-wrap">
        <div class="services__pillar-bg"></div>
        <div class="services__pillar">
            <div class="services__pillar-item-wrap services__pillar-item-wrap_title">
                <div class="services__pillar-title">Услуги</div>
                <div class="services__pillar-subtitle-wrap">
                    <div class="services__pillar-subtitle">Комплексное создание интерьера и экстерьера, начиная от
                        дизайн проекта, и заканчивая 3D визуализаций. На всех этапах с вами работают не менеджеры, а
                        наши специалисты. Так же предоставляются услуги авторского надзора.</div>
                </div>
            </div>
            <div class="services__pillar-item-wrap services__pillar-item-wrap_1">
                <div class="services__pillar-item-bg services__pillar-item-bg_1"></div>
                <div class="services__pillar-item-text-wrap services__pillar-item-text-wrap_1">
                    <h2 class="services__pillar-item-text-title">Индивидуальный дизайн-проект
                        <div class="services__pillar-item-text-title-info">
                            <div class="services__pillar-item-text-title-info-text-wrap services__pillar-item-text-title-info-text-wrap_1">
                                <div class="services__pillar-item-text-title-info-text">
                                    • Уточнив Ваши пожелания по дизайну мы рассчитаем стоимость всех работ.
                                    <br>
                                    <br>
                                    • Дизайн проект с техническими чертежами и 3D визуализацей - от 700 р м² в
                                    зависимости от особенностей помещения.
                                </div>
                            </div>
                        </div>
                    </h2>
                    <div class="services__pillar-item-text">Наши специалисты следят за новыми тенденциями, имеют чувство
                        вкуса и обладают умением слышать клиента, что позволяет разработать для вас любой проект от
                        консервативной классики до эксклюзивного лофта.</div>
                </div>
                <div class="services__pillar-item-foto services__pillar-item-foto_1"></div>
            </div>

            <div class="services__pillar-item-wrap services__pillar-item-wrap_2">
                <div class="services__pillar-item-bg services__pillar-item-bg_2"></div>
                <div class="services__pillar-item-text-wrap services__pillar-item-text-wrap_2">
                    <h2 class="services__pillar-item-text-title">3D визуализация интерьера
                        <div class="services__pillar-item-text-title-info">
                            <div class="services__pillar-item-text-title-info-text-wrap services__pillar-item-text-title-info-text-wrap_2">
                                <div class="services__pillar-item-text-title-info-text">
                                    • Мы можем подготовить для Вас 3D визуализацию под уже имеющийся дизайн-проект или
                                    оформить Вашу личную идею.
                                    <br>
                                    <br>
                                    • Стоимость - от 300р м².
                                </div>
                            </div>
                        </div>
                    </h2>
                    <div class="services__pillar-item-text">Основная деятельность нашей компании — визуализация
                        интерьеров и экстерьеров. В наши услуги входит моделирование квартир, домов, офисов, кафе,
                        ресторанов и производственных площадей.
                    </div>
                </div>
                <div class="services__pillar-item-foto services__pillar-item-foto_2"></div>
            </div>

            <div class="services__pillar-item-wrap services__pillar-item-wrap_3">
                <div class="services__pillar-item-bg services__pillar-item-bg_3"></div>
                <div class="services__pillar-item-text-wrap services__pillar-item-text-wrap_3">
                    <h2 class="services__pillar-item-text-title">Индивидуальные чертежи в AutoCAD
                        <div class="services__pillar-item-text-title-info">
                            <div class="services__pillar-item-text-title-info-text-wrap services__pillar-item-text-title-info-text-wrap_1">
                                <div class="services__pillar-item-text-title-info-text">
                                    • Бесплатно, входит в стоимость при заказе дизайн-проекта.
                                </div>
                            </div>
                        </div>
                    </h2>
                    <div class="services__pillar-item-text">Вместе с дизайн проектом разрабатываются и индивидуальные
                        технические чертежи необходимые для просчета стоимости проекта и его реализации.
                    </div>
                </div>
                <div class="services__pillar-item-foto services__pillar-item-foto_3"></div>
            </div>
        </div>
    </div>
</div>

app/templates/include/thn-popup.html
<div class="tnh-popup__wrap tnh-popup__wrap_close">
    <div class="tnh-popup">
        <div class="tnh-popup__esc"></div>
        <div class="tnh-popup__text">Спасибо! <br> В ближайшее время мы свяжемся с вами!</div>
    </div>
</div>

app/templates/include/works.html
{% load static %}

<div class="works__wrap">
    <div id="about" class="works__ankor"></div>
    <div class="works__bg-wrap">
        <div style="background-image: url({% static 'img/works/1.jpg' %})"  class="works__bg"></div>
        <div style="background-image: url({% static 'img/works/2.jpg' %})"  class="works__bg"></div>
        <div style="background-image: url({% static 'img/works/3.jpg' %})"  class="works__bg"></div>
        <div style="background-image: url({% static 'img/works/4.jpg' %})"  class="works__bg"></div>
        <div style="background-image: url({% static 'img/works/5.jpg' %})"  class="works__bg"></div>
        <div style="background-image: url({% static 'img/works/6.jpg' %})"  class="works__bg"></div>
        <div style="background-image: url({% static 'img/works/7.jpg' %})"  class="works__bg"></div>
        <div style="background-image: url({% static 'img/works/8.jpg' %})"  class="works__bg"></div>
        <div style="background-image: url({% static 'img/works/9.jpg' %})"  class="works__bg"></div>
        <div style="background-image: url({% static 'img/works/10.jpg' %})"  class="works__bg"></div>
        
        <div class="works__slider">
            <div class="works__slider-text">DESIGN</div>
        </div>
    </div>
    <h2 class="works__title">Информация о нас:</h2>
    <div class="works__text">
        <div class="works__text-wrap works__text-wrap_project">
            <div data-count='25' class="works__text-count">25</div>
            <div class="works__text-title">Проектов</div>
        </div>

        <div class="works__text-wrap works__text-wrap_rooms">
            <div data-count='172' class="works__text-count works__text-count_rooms">172</div>
            <div class="works__text-title">Помещений</div>
        </div>

        <div class="works__text-wrap works__text-wrap_furniture">
            <div class="works__text-title works__text-title_furniture">Мебели</div>
            <div data-count='1220' class="works__text-count works__text-count_furniture">1202</div>
        </div>
        <div class="works__text-wrap works__text-wrap_city">
            <div class="works__text-title works__text-title_city">Городов</div>
            <div data-count='12' class="works__text-count works__text-count_city">12</div>
        </div>
        <div class="works__text-wrap works__text-wrap_cli">
            <div class="works__text-title works__text-title_cli">Клиентов</div>
            <div data-count='18' class="works__text-count works__text-count_cli">18</div>
        </div>

        <div class="works__text-wrap works__text-wrap_cats">
            <div data-count='4613' class="works__text-count works__text-count_cats">4613</div>
            <div class="works__text-title"> <strong>М²</strong></div>
        </div>
    </div>
    <div class="works__counter"></div>
</div>

app/templates/mobile/include/contact-footer.html
<div class="footer__wrap">
        <div class="footer__slider-wrap">
            <div class="footer">
                <div class="footer__slider-wrap-wrap">
                    <a href="tel:89180555202" class="footer__item footer__contacts">8-918-670-71-73</a>
                    <a href="mailto:info@aristovdesign.ru"
                        class="footer__item footer__form-contacts">info@aristovdesign.ru</a>
                    <a href="{{instagram}}" class="footer__item footer__instagram"
                        target="__blank">aristovdesign</a>
                </div>
            </div>
        </div>
    </div>

app/templates/mobile/include/contentmain.html
{% load static %}

<div class="content">
    <div class="main-view__wrap">
        <div class="main-view__slider-wrap">
             <div class="main-view__slider-wrap">
                 {% for work in works %}
                     <div class="main-view__slider-item">
                         <div data-href='#_{{ work.id }}' class="main-view__slider-item-photo"
                              style="background-image: url({% if work.photo_mobile %} {{work.photo_mobile.url}} {% else %} {{ work.photo.url}} {% endif %});"></div>
                         <div class="main-view__slider-item-title">{{ work.title }}</div>
                     </div>
                 {% endfor %}
             </div>
        </div>
        <a href="/" class="main-view__link main-view__link_top">Перейти к проекту</a>
    </div>
</div>

app/templates/mobile/portfolio.html
{% extends 'mobile/main.html' %}
{% load static %}


{% block title %}
    <title>AristovDesign – 3D визуализация и дизайн | Портфолио</title>
{% endblock %}

{% block meta %}
    <meta name=description content="AristovDesign - 3D дизайн и визуализация интерьера.">
    <meta name=keywords content="3D дизайн, 3D визуализация">
{% endblock %}
{% block header %}
{% include 'mobile/include/header.html' with page='portfolio' %}
{% endblock %}

{% block content %}
<div class="portfolio__wrap">
    <div class="portfolio__title">Работы</div>

    {% for work in works %}
    <div class="portfolio__slider__title">{{ work.title }}</div>
    <div id="{{ work.translit }}"
        class="portfolio {% if forloop.counter|divisibleby:'2' %} portfolio_right {% endif %}">
        <div class="portfolio__slider__wrap">
            <div id="{{work.id}}" class="portfolio__ankor"></div>
            <div class="portfolio__slider">
                <div style="background-image: url({{ work.photo.url }});" class="portfolio__slider__item"></div>
                {% for image in work.image_set.all %}
                <div style="background-image: url({{ image.image.url }});" class="portfolio__slider__item"></div>
                {% endfor %}
            </div>
        </div>
        <div class="portfolio__text">
            <div class="portfolio__subtitle">{{ work.description }}</div>
            <!-- <div class="portfolio__add">Подробнее</div> -->
            <div class="portfolio__style">{{ work.style }}</div>
        </div>
    </div>
    {% endfor %}



</div>
{%  endblock %}

app/templates/portfolio.html
{% extends 'main.html' %}
{% load static %}


{% block title %}
    <title>AristovDesign – 3D визуализация и дизайн | Портфолио</title>
{% endblock %}

{% block header %}
{% include 'include/header.html' with page="portfolio" %}
{% endblock %}
{% block meta %}
    <meta name=description content="AristovDesign - 3D дизайн и визуализация интерьера.">
    <meta name=keywords content="3D дизайн, 3D визуализация">
{% endblock %}

{% block content %}
<div class="portfolio__wrap">
    <div class="portfolio__pillar">
        <h1 class="portfolio__pillar-title">Портфолио</h1>
    </div>
        {% for work in works %}
        <div id="{{ work.id }}" class="portfolio {% if forloop.counter|divisibleby:'2' %} portfolio_right {% endif %}">
            <div class="portfolio__slider__wrap">
                <div class="portfolio__slider">
                    <div style="background-image: url({{ work.photo.url }});" class="portfolio__slider__item"></div>
                    {% for image in work.image_set.all %}
                        <div style="background-image: url({{ image.image.url }});" class="portfolio__slider__item"></div>
                    {% endfor %}
                </div>
            </div>
            <div class="portfolio__text">
                <div class="portfolio__title">{{ work.title }}</div>
                <div class="portfolio__subtitle">{{ work.description }}</div>
                <div class="portfolio__style">{{ work.style }}</div>
                <!-- <div class="portfolio__add">Подробнее</div> -->
            </div>
        </div>
        {% endfor %}
    </div>
{%  endblock %}